title: Découvrez les séjours autour de chez vous
author: Marie-Aline Millot 
email: mariealine@weekendesk.fr
description: >-
  De magnifiques et superbes endroits n'attendent que vous !
baseurl:  # the subpath of your site, e.g. /blog
url: https://mariealine.github.io/ubuild-jekyll/

# Build settings
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus

