title: 100 kms around me
author: Marie-Aline Millot 
email: mariealine@weekendesk.fr
description: >-
  "100kms around me" allow you to find the best place to go away and enjoy a short stay. Enjoy !
baseurl: "https://mariealine.github.io/ubuild-jekyll/" # the subpath of your site, e.g. /blog
url: https://mariealine.github.io/ubuild-jekyll/

# Build settings
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
