---
title: 100 kms around me
author: Marie-Aline Millot
email: mariealine@weekendesk.fr
description: '"100kms around me" allow you to find the best place to go away and enjoy
  a short stay. Enjoy !'
baseurl: ''
url: https://mariealine.github.io/ubuild-jekyll/
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
